source 'https://github.com/CocoaPods/Specs.git'

target 'Aubergine', :exclusive => true do
  pod "Aubergine", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Aubergine", :path => "../"
end
